### ISSUE TITLE
安装后有问题啊，运行不了啊，vendor 里面没有 yiisoft文件夹和autoload.php文件

### ISSUE THREAD

**Issue by asialong** [daixianceng/xiaoego.com#2]
安装后有问题啊，运行不了啊，vendor 里面没有 yiisoft文件夹和autoload.php文件

**Comment by daixianceng** [comment]
确保你运行了composer install并且成功了，没有yiisoft文件夹一定是composer未执行成功

**Comment by asialong** [comment]
这样啊，那我再试试
